# -*- coding: utf-8 -*-
#
# DO NOT EDIT THIS FILE MANUALLY.
#
# This file is automatically generated by the 'generate_strings.py' script
# from the content of a YAML file. It is used by gettext to extract
# translatable strings from data files.
#
import gettext
_ = gettext.gettext

# --- Strings from data file ---
_('Accessibility')
_('AppStore')
_('Audio Converter')
_('Big Store')
_('BigLinux Info')
_('BigLinux Settings')
_('Brave')
_('Choose Your Avatar')
_('Choose your default browser')
_('Chrome')
_('Chromium')
_('Configure voice')
_('Control Center')
_('Discover some features')
_('Display Settings')
_('Donate')
_('Donation and Social Networks')
_('Driver Installation and Hardware Information')
_('Driver Manager')
_('Edge')
_('Falkon')
_('Firefox')
_('Forum')
_('Initial Settings')
_('Install or Remove Drivers and Firmwares easily.')
_('KDE Connect')
_('KDE Connect is an application that facilitates wireless communication and data transfer between devices on local networks. Available on the Google Play Store for Android and the Apple Store for iPhone.')
_('Kernel Manager')
_('Language Packs')
_('Librewolf')
_('Network Info')
_('Noise Reduction')
_('OCR to PDF')
_('Opera')
_('Our platform is collaborative, join this evolution.')
_('PlayStore')
_('Printers')
_('Session and Themes')
_('Set your default browser.')
_('Telegram')
_('Video Converter')
_('Vivaldi')
_('We provide comprehensive settings for you to select in an extremely simple way.')
_('WebApps')
_('YouTube')
_('Your donation is very important for the project and follow us on social media.')
